### PR TITLE
convert date to iso 8061 format

### LINKED ISSUE #548: AddProductColumnTypesTest failing for OutOfproc
Test fails with internal server error: System.Private.CoreLib: Exception while executing function: Functions.AddProductColumnTypes. Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Core Microsoft SqlClient Data Provider: Conversion failed when converting date and/or time from character string.

### PR DESCRIPTION
**Pull request by MaddyDev**
Fixes #548 
The OOP function sends the date in the below format:
2022-12-01T02:39:56.098554Z and Sql fails with the following error: System.Private.CoreLib: Exception while executing function: Functions.AddProductColumnTypes. Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Core Microsoft SqlClient Data Provider: Conversion failed when converting date and/or time from character string.

In order for SQL to accept that format, datatype of that field should be DateTime2. Explicitly converting the datetime to ISO 8061 with milliseconds: yyyy-MM-ddTHH:mm:ss.fffZ and sending it so it's acceptable on SQL server.

### CODE REVIEW

File: test-outofproc/AddProductColumnTypes.cs [hunk 1]
```diff
@@ -26,7 +26,7 @@ public static class AddProductColumnTypes
             var product = new ProductColumnTypes()
             {
                 ProductID = int.Parse(queryStrings["productId"], null),
-                Datetime = DateTime.UtcNow.Date,
+                Datetime = DateTime.Parse(DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ", System.Globalization.CultureInfo.InvariantCulture)),
                 Datetime2 = DateTime.UtcNow
```
[the remark this answers is not in the document]
Comment (MaddyDev) [reply test-outofproc/AddProductColumnTypes.cs:30]: The error is caused due to the fact that Datetime fields data type is DateTime. DateTime2 fileds data type is DateTime2 and sql accepts the format being sent for that datatype. DateTime data type only accepts upto 3 digits for the milliseconds hence fails with conversion error, so the explicit conversion for that field is required.

**Review by VasuBhog — APPROVED** [review]

File: test-outofproc/AddProductColumnTypes.cs [hunk 2]
```diff
@@ -26,7 +26,7 @@ public static class AddProductColumnTypes
             var product = new ProductColumnTypes()
             {
                 ProductID = int.Parse(queryStrings["productId"], null),
-                Datetime = DateTime.UtcNow.Date,
+                Datetime = DateTime.ParseExact(DateTime.UtcNow.ToString(System.Globalization.CultureInfo.InvariantCulture), "yyyy-MM-ddTHH:mm:ss.fffZ", null),
```
Comment (chlafreniere) [inline test-outofproc/AddProductColumnTypes.cs:29]: Out of curiosity have you tried using https://learn.microsoft.com/en-us/dotnet/api/system.data.sqltypes.sqldatetime?view=net-7.0?

Does something like this work?

```
DateTime = new SqlDateTime(DateTime.UtcNow).ToSqlString(),
```

Comment (MaddyDev) [reply test-outofproc/AddProductColumnTypes.cs]: Didn't know about SqlDateTime, going to give it a try and see if it works. Thanks for the suggestion!

**Review by lucyzhang929 — APPROVED** [review]
