### PR TITLE
Skip empty where clause execution on trigger

### LINKED ISSUE #1108: Failed to renew leases due to exception: Exception message: Incorrect syntax near ';'.
The SQL trigger generates invalid T-SQL intermittently while renewing leases, causing false alerts in the monitoring system. The issue does not affect the functionality of the SQL Trigger. 
SQL trigger raising Microsoft.Data.SqlClient.SqlException. Exception message: Incorrect syntax near \';\'

Below are the logs from the system:

Exception executing query. Message=Incorrect syntax near ';'.
Query=
DECLARE @result int;
EXEC @result = sp_getapplock @Resource = '_az_func_Trigger',
@LockMode = 'Exclusive',
@LockTimeout = 30000
IF @result < 0
BEGIN
RAISERROR('Unable to acquire exclusive lock on _az_func_Trigger. Result = %d', 16, 1, @result)
END;

UPDATE [az_func].[Leases_cacf2bceb5090ff5_1845581613]
SET _az_func_LeaseExpirationTime = DATEADD(second, 60, SYSDATETIME())
WHERE ;

Refer [Icm](https://portal.microsofticm.com/imp/v5/incidents/details/517530853/summary) for more information.

### PR DESCRIPTION
**Pull request by MaddyDev**
Return null when match condition resolves to empty instead of sending in the empty where clause.

Fixes #1108

### CODE REVIEW

File: src/TriggerBinding/SqlTableChangeMonitor.cs [hunk 1]
```diff
@@ -981,6 +983,7 @@ private SqlCommand BuildRenewLeasesCommand(SqlConnection connection, SqlTransact
             if (string.IsNullOrEmpty(matchCondition))
             {
                 this._logger.LogError($"MatchCondition resolved to empty with '{this._rowsToProcess.Count}' rowsToProcess.");
+                return null;
```
Comment (Charles-Gagnon) [inline src/TriggerBinding/SqlTableChangeMonitor.cs:986]: suggestion: Add comment explaining why we want to return null in this case

File: src/TriggerBinding/SqlTableChangeMonitor.cs [hunk 2]
```diff
@@ -981,6 +983,7 @@ private SqlCommand BuildRenewLeasesCommand(SqlConnection connection, SqlTransact
             if (string.IsNullOrEmpty(matchCondition))
             {
                 this._logger.LogError($"MatchCondition resolved to empty with '{this._rowsToProcess.Count}' rowsToProcess.");
```
Comment (Charles-Gagnon) [inline src/TriggerBinding/SqlTableChangeMonitor.cs:985]: Do we want to add a telemetry event for when this occurs?

**Review by Charles-Gagnon — APPROVED** [review]

**Review by chlafreniere — APPROVED** [review]
