### PR TITLE
fix casing issue when sql table is case insensitive

### LINKED ISSUE #232: `Cannot insert the value NULL into column <COLUMN_NAME>` on SQL output binding in Javascript function
I understand that this extension supports Javascript/Typescript from `v.0.1.304-preview`.
https://github.com/Azure/azure-functions-sql-extension/releases/tag/v.0.1.304-preview

Do you have any samples in Javascript/Typescript?

### PR DESCRIPTION
**Pull request by MaddyDev**
Fixes #232  where the column names are case insensitive, we are building the sql query converting the columns to lowercase but the javascript object keys are being passed as defined and the sql query is expecting lowercased values. 

Fix: Added an extra step to convert the JObjects keys to lower case and passed that to the sql query.
Tried using the JsonSerializerSettings and passing the NamingStrategy to convert property names to lowercase but that was not working and still returned keys as is. Alternatively manually updated the properties to lower case by iterating through them.

### CODE REVIEW

File: src/SqlAsyncCollector.cs [hunk 1]
```diff
@@ -313,6 +313,10 @@ private static void GenerateDataQueryForMerge(TableInformation table, IEnumerabl
                 else
                 {
                     // ToDo: add check for duplicate primary keys once we find a way to get primary keys.
+                    if (table.Comparer == StringComparer.OrdinalIgnoreCase)
+                    {
+                        ChangePropertiesToLowerCase(JObject.Parse(row.ToString()));
```
Comment (Charles-Gagnon) [inline src/SqlAsyncCollector.cs:318]: How is this actually changing anything? You convert the JObject to a string and then turn it back into a JObject which you then modify. But the original row isn't modified at all...

File: src/SqlAsyncCollector.cs [hunk 2]
```diff
@@ -313,6 +313,10 @@ private static void GenerateDataQueryForMerge(TableInformation table, IEnumerabl
                 else
                 {
                     // ToDo: add check for duplicate primary keys once we find a way to get primary keys.
+                    if (table.Comparer == StringComparer.OrdinalIgnoreCase)
```
Comment (Charles-Gagnon) [inline src/SqlAsyncCollector.cs:316]: Comments explaining why this is necessary

File: src/SqlAsyncCollector.cs [hunk 3]
```diff
@@ -324,6 +328,18 @@ private static void GenerateDataQueryForMerge(TableInformation table, IEnumerabl
             newDataQuery = $"WITH {CteName} AS ( SELECT * FROM OPENJSON({RowDataParameter}) WITH ({string.Join(",", bracketColumnDefinitionsFromItem)}) )";
         }
 
+        private static void ChangePropertiesToLowerCase(JObject jsonObject)
+        {
+            foreach (JProperty property in jsonObject.Properties().ToList())
+            {
+                if (property.Value.Type == JTokenType.Object)
```
Comment (Charles-Gagnon) [inline src/SqlAsyncCollector.cs:335]: Seems better to actually check the C# type here (make sure it's actually a JObject)

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: src/SqlAsyncCollector.cs (hunk 3 above)
Comment (MaddyDev) [reply src/SqlAsyncCollector.cs:336]: I didn't understand what you mean?

Comment (Charles-Gagnon) [reply src/SqlAsyncCollector.cs:336]: `property.Value.GetType() == typeof(JObject)`

It seems odd to rely on Value.Type when you have the actual object - especially since we then cast it to JObject right below anyways.

File: src/SqlAsyncCollector.cs [hunk 4]
```diff
@@ -313,6 +313,11 @@ private static void GenerateDataQueryForMerge(TableInformation table, IEnumerabl
                 else
                 {
                     // ToDo: add check for duplicate primary keys once we find a way to get primary keys.
+                    // lower case the json keys if sql table is case insensitive since the query we built expects everything lowercased.
+                    if (table.Comparer == StringComparer.OrdinalIgnoreCase)
+                    {
+                        ChangePropertiesToLowerCase(row as JObject);
```
Comment (Charles-Gagnon) [inline src/SqlAsyncCollector.cs:319]: So we already have JsonSerializerSettings in table information - which we then use to generate the rowData. Why isn't that handling converting it to lowercase? It would be good to look into using that same logic instead of doing this custom logic here.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

File: src/SqlAsyncCollector.cs (hunk 4 above)
Comment (MaddyDev) [reply src/SqlAsyncCollector.cs:319]: I already tried that before coming to this solution, it was not changing the case and I was not able to find out why.

File: src/SqlAsyncCollector.cs (hunk 3 above)
Comment (MaddyDev) [reply src/SqlAsyncCollector.cs]: I was trying typeof(property.Value) == typeof(JObject) and it was showing me a compiler error, I need to learn when to use GetType vs typeof :|

File: src/SqlAsyncCollector.cs (hunk 4 above)
Comment (Charles-Gagnon) [reply src/SqlAsyncCollector.cs:319]: Alright, so I looked into this and the root issue here is because contract resolvers are ignored by default when serializing JObjects (https://web.archive.org/web/20171005181503/http://json.codeplex.com/workitem/23853).

I looked around and unfortunately there doesn't seem to be a clean way to change this behavior - so manually going through and updating the property names like you have is probably our best solution.

**Review by Charles-Gagnon — APPROVED** [review]

File: src/SqlAsyncCollector.cs [hunk 5]
```diff
@@ -315,6 +315,12 @@ private static void GenerateDataQueryForMerge(TableInformation table, IEnumerabl
                 else
                 {
                     // ToDo: add check for duplicate primary keys once we find a way to get primary keys.
+                    // JObjects ignore serializer settings (https://web.archive.org/web/20171005181503/http://json.codeplex.com/workitem/23853)
+                    // so we have to manually convert property names to lower case before inserting into the query in that case
```
Comment (chlafreniere) [inline src/SqlAsyncCollector.cs:319]: What about case sensitive collations?

Comment (chlafreniere) [reply src/SqlAsyncCollector.cs:319]: (even if this works, clarifying that it works in a comment would be helpful to readers)

Comment (Charles-Gagnon) [reply src/SqlAsyncCollector.cs:319]: Case sensitive has always been up to the caller to get right - we have no way of knowing what the expected case is. Case insensitive is just always converted to lower case for comparisons for convenience (since the casing still has to be the same, but we can control that for case insensitive)

https://github.com/Azure/azure-functions-sql-extension/blob/main/src/SqlAsyncCollector.cs#L526

**Review by chlafreniere — APPROVED** [review]

File: src/SqlAsyncCollector.cs (hunk 5 above)
Comment (chlafreniere) [reply src/SqlAsyncCollector.cs:319]: Thanks @Charles-Gagnon
