### PR TITLE
Fix Integration Tests in Builds

### LINKED ISSUE #223: Getting "Connection Refused" errors in Integration Tests
e.g.

https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=148379&view=logs&j=911909e3-f132-51e7-cb10-4a0c4ab1d143&t=c2542b5c-8cb4-5274-ab21-603e725c31e3

```
[xUnit.net 00:01:35.67]     Microsoft.Azure.WebJobs.Extensions.Sql.Tests.Integration.SqlOutputBindingIntegrationTests.AddProductsCollectorTest [FAIL]
  Failed Microsoft.Azure.WebJobs.Extensions.Sql.Tests.Integration.SqlOutputBindingIntegrationTests.AddProductsCollectorTest [2 s]
  Error Message:
   System.AggregateException : One or more errors occurred. (Connection refused)
---- System.Net.Http.HttpRequestException : Connection refused
-------- System.Net.Sockets.SocketException : Connection refused
  Stack Trace:
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, Cancellation*** cancellation***)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Azure.WebJobs.Extensions.Sql.Tests.Integration.SqlOutputBindingIntegrationTests.AddProductsCollectorTest() in /home/vsts/work/1/s/test/Integration/SqlOutputBindingIntegrationTests.cs:line 81
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancellation*** cancellation***)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, Cancellation*** cancellation***)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Cancellation*** cancellation***)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Cancellation*** cancellation***)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, Cancellation*** cancellation***)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Cancellation*** cancellation***)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, Cancellation***Source cts, Boolean disposeCts)
   at Microsoft.Azure.WebJobs.Extensions.Sql.Tests.Integration.IntegrationTestBase.SendGetRequest(String requestUri, Boolean verifySuccess) in /home/vsts/work/1/s/test/Integration/IntegrationTestBase.cs:line 248
   at Microsoft.Azure.WebJobs.Extensions.Sql.Tests.Integration.SqlOutputBindingIntegrationTests.SendOutputRequest(String functionName, IDictionary`2 query) in /home/vsts/work/1/s/test/Integration/SqlOutputBindingIntegrationTests.cs:line 32
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, Cancellation*** cancellation***)
  Standard Output Messages:
```

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #223 

A couple of different issues:

- We weren't waiting long enough for the function host to be started, which is why there were the HTTP connection issues. After printing out `Job host started`, it then will print out `Functions:` followed by the function name + URL -- and only then will an endpoint is available to connect to. Looking for the API url to be output to stdout appears to fix this for now. Example:

```
[2022-04-12T09:05:34.851Z] Job host started
Functions:
        GetProductsStoredProcedureFromAppSetting: [GET] http://localhost:7071/api/getproductsbycost
```

- There were lots of changes in the storage package from 4.0.3 to 5.0.0. While going back to 4.0.4 worked ([proof](https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=149520&view=results)), using latest is probably best. Without azurite always running, unfortunately, the following message was emitted from the logs (after the first fix):

```
[2022-04-12T07:58:11.029Z] There was an error performing a read operation on the Blob Storage Secret Repository. Please ensure the 'AzureWebJobsStorage' connection string is valid.
[2022-04-12T07:58:11.088Z] Initialization cancellation requested by runtime.
```
(sample build [here](https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=149546&view=logs&j=eacbd837-81c1-576f-20cf-892b6bb5d752&t=ab12bd64-f710-5a9b-47f2-e57b34a17b04))

Always running azurite for the integration tests solves this issue. I don't love it, but it appears somewhere down the line, this is now enforced in the new version of the package. I played with some solutions found on [StackOverflow](https://stackoverflow.com/questions/67728499/azure-functions-there-was-an-error-performing-a-read-operation-on-the-blob-stor), but couldn't get them working myself.

### CODE REVIEW

File: test/Integration/IntegrationTestBase.cs [hunk 1]
```diff
@@ -193,13 +193,13 @@ protected void StartFunctionHost(string functionName, bool useTestFolder = false
...
                 // since sometimes the host can take a little while to fully start up
-                if (e.Data.Contains("Job host started"))
+                if (e != null && !string.IsNullOrEmpty(e.Data) && e.Data.Contains($"http://localhost:{this.Port}/api"))
                 {
                     taskCompletionSource.SetResult(true);
                 }
             };
             this.TestOutput.WriteLine($"Waiting for Azure Function host to start...");
-            taskCompletionSource.Task.Wait();
+            taskCompletionSource.Task.Wait(60000);
```
Comment (lucyzhang929) [inline test/Integration/IntegrationTestBase.cs:202]: Do we still need to wait 60 seconds after the endpoint is printed?

**Review by lucyzhang929 — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]

File: test/Integration/IntegrationTestBase.cs (hunk 1 above)
Comment (Charles-Gagnon) [reply test/Integration/IntegrationTestBase.cs:202]: That's just the timeout so we don't wait forever if it doesn't finish starting up

https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.wait?view=net-6.0#system-threading-tasks-task-wait(system-int32)

Comment (lucyzhang929) [reply test/Integration/IntegrationTestBase.cs:202]: Ah gotcha, thanks!

**Review by MaddyDev — APPROVED** [review]
